version: '3'
services:
  db:
    image: 821924379270.dkr.ecr.us-east-1.amazonaws.com/note-keeper-db:0.1
    environment:
      - POSTGRES_USER=postgres # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=password # The PostgreSQL password (useful to connect to the database)
      - POSTGRES_DB=note-keeper # The PostgreSQL default database (automatically created at first launch)
      - PGDATA=/var/lib/postgresql/data/pgdata
    # expose:
    #   - "5432"
    # ports:
    #   - "5432:5432"
    # volumes:
    #   - ./DockerDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: awslogs
      options:
        awslogs-group: note-keeper
        awslogs-region: us-east-1
        awslogs-stream-prefix: note-keeper-db

  backend:
    image: 821924379270.dkr.ecr.us-east-1.amazonaws.com/note-keeper-backend:0.1
    ports:
      - "9000:9000"
    # expose:
    #   - "9000"
    environment:
      - POSTGRES_PASSWORD=password
    command: ["./wait-for-postgres.sh", "localhost","--", "/app/server"]
    # depends_on:
    #   - db
    logging:
      driver: awslogs
      options:
        awslogs-group: note-keeper
        awslogs-region: us-east-1
        awslogs-stream-prefix: note-keeper-backend

  frontend:
    image: 821924379270.dkr.ecr.us-east-1.amazonaws.com/note-keeper-frontend:0.1 
    ports:
      - "443:443"
    command: ["http-server", "-S", "-P", "http://localhost:9000"]
    logging:
      driver: awslogs
      options:
        awslogs-group: note-keeper
        awslogs-region: us-east-1
        awslogs-stream-prefix: note-keeper-frontend
