version: '2'
services:
  db:
    build: DockerDB/.
    environment:
      # - POSTGRES_USER=postgres # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=password # The PostgreSQL password (useful to connect to the database)
      # - POSTGRES_DB=note-keeper # The PostgreSQL default database (automatically created at first launch)
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  backend:
    build: note-keeper-backend/.
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
    command: ["./wait-for-postgres.sh", "db","--", "/app/server"]
